name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # You can choose the OS that fits your EC2 instance

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_HOST: ubuntu@13.40.19.4
      SSH_IDENTITY_FILE: ~/.ssh/id_rsa
      PROJECT_NAME: ${{ github.event.repository.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key file and directory
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: /bin/bash -e {0}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into EC2 and delete existing files
      run: |
        ssh -vvv -o "StrictHostKeyChecking=no" -i $SSH_IDENTITY_FILE $SSH_HOST << EOF
          # Remove existing files and directories in the destination path
          echo "ls -l"
          
          sudo mkdir -p /projects/$PROJECT_NAME
        EOF
        echo "I did itttt"
