name: GitHub Action

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'version tag'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH key file and directory
        run: |
          mkdir -p /home/runner/.ssh
          echo "" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          eval "$(ssh-agent -s)"
        shell: /bin/bash -e {0}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          echo "${{ secrets.CLIENT_OVPN }}" > client.ovpn
          
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: client.ovpn

      - name: SSH into EC2 and delete existing files
        run: |
          sshpass -p "\!QW@3er4@.Fl0R#n@\!" ssh -v myidentitypass.local\\florence@10.70.0.114 << EOF
            whoami
          EOF
