name: Ogaboga

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'version tag'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPN_USER: deploymentagent
      VPN_PWD: '!QW@3er4@.d3PloY12'
      VPN_HOST: myidentitypass.local
      VPN_PORT: 8050

    steps:
    - name: Checkout code
      uses: horellana/openconnect@v1.0.1
