name: GitHub Action

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'version tag'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "10.70.0.114"
          username: "myidentitypass.local\\\\florence"
          password: "!QW@3er4@.Fl0R#n@!"
          script: whoami
