name: Ogaboga

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'version tag'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Wine (for running AutoHotkey)
        run: sudo apt-get update && sudo apt-get install wine -y
      - name: Start FortiClient VPN
        run: |
          echo "Starting FortiClient VPN..."
          echo "${{ vars.AHKFILE }}" > forticlient_auto_connect.ahk
          wine AutoHotkey.exe forticlient_auto_connect.ahk # Replace with your AutoHotkey script
      - name: Run CI/CD tasks behind VPN
        run: |
          echo "Running CI/CD tasks behind FortiClient VPN..."
          # Execute your CI/CD tasks here
          # For example:
          # npm install
          # npm run build
          # ./deploy.sh
      - name: Stop FortiClient VPN (if needed)
        run: |
          # If you need to stop the VPN connection after CI/CD tasks
          echo "Stopping FortiClient VPN..."
          # Command to stop the FortiClient VPN connection
